package main

import (
	"context"
	"flag"
	"net/http"

	"github.com/zeromicro/go-zero/core/conf"
	"github.com/zeromicro/go-zero/core/logx"
	"github.com/zeromicro/go-zero/core/stores/redis"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/trace"
	"github.com/zeromicro/go-zero/rest"
	"github.com/zeromicro/go-zero/rest/httpx"
)

// Config mirrors etc/user-api.yaml.
type Config struct {
	rest.RestConf
	Redis     redis.RedisConf
	Mysql     sqlx.SqlConf
	Telemetry trace.Config
}

type ServiceContext struct {
	Config Config
	DB     sqlx.SqlConn
	Redis  *redis.Redis
}

func NewServiceContext(c Config) *ServiceContext {
	return &ServiceContext{
		Config: c,
		DB:     sqlx.NewMysql(c.Mysql.DataSource),
		Redis:  redis.MustNewRedis(c.Redis),
	}
}

// Register routes; normally generated by goctl.
func RegisterHandlers(server *rest.Server, ctx *ServiceContext) {
	server.AddRoute(rest.Route{
		Method:  http.MethodGet,
		Path:    "/ping",
		Handler: PingHandler(ctx),
	})
}

func PingHandler(ctx *ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		logger := logx.WithContext(r.Context())
		logger.Infof("ping")
		httpx.OkJsonCtx(r.Context(), w, map[string]string{"message": "pong"})
	}
}

func main() {
	var configFile string
	flag.StringVar(&configFile, "f", "etc/user-api.yaml", "the config file")
	flag.Parse()

	var c Config
	conf.MustLoad(configFile, &c)
	logx.MustSetup(c.Log)

	closer := trace.StartAgent(c.Telemetry)
	defer closer.Close()

	ctx := NewServiceContext(c)
	defer func() {
		logx.Close()
		if ctx.Redis != nil {
			ctx.Redis.Close()
		}
	}()

	server := rest.MustNewServer(c.RestConf)
	defer server.Stop()

	server.Use(rest.RecoverHandler())
	RegisterHandlers(server, ctx)

	logx.Infof("Starting rest server at %s:%d...", c.Host, c.Port)
	server.Start()
}
